### PR TITLE
Bigmaps WIP

### PR DESCRIPTION
**Pull request by Pockets-byte**
I'm making the metagame maps bigger. not much more to say. still lots of work to do, ~~only~~ FredeligPlains, Ketanot Hills and part of metankora highlands done so far

- [x] FredeligPlains
- [x] Ketanot Hills
- [ ] Metankora Highlands
- [ ] Mt. Imdunt
- [ ] Burraki Desert
- [ ] Rayvord Tundra
- [ ] Dvorak Caves
- [ ] Rhias Forest
- [ ] Slodran Wilderness
- [ ] Vesod Plains
- [ ] Yskely Mountains
- [ ] Zekarra Lowlands

### CODE REVIEW

**Comment by ArmolitskiyCarpoeb** [comment]
Omg. How will this affect performance?

**Comment by Causeless** [comment]
> Omg. How will this affect performance?

With the optimizations coming in Pre-5, it won't.

**Comment by Pockets-byte** [comment]
for the sake of my sanity, and finishing this on time, I"m going to uniformly scale things in the future, probably 6000x2000
the maps can always be increased in size later, and it'll probably be easier to do a second pass and add 2000 pixels on either side than make 6000 pixels worth of map from scratch

**Comment by Causeless** [comment]
@Pockets-byte If we want to get this in, it's beocming tricky because there's a lot of merge conflicts popping up. I'm not averse to including these maps but they should probably be as slightly smaller PRs of a few maps each if you don't feel comfortable getting these finished.

**Comment by Pockets-byte** [comment]
> @Pockets-byte If we want to get this in, it's beocming tricky because there's a lot of merge conflicts popping up. I'm not averse to including these maps but they should probably be as slightly smaller PRs of a few maps each if you don't feel comfortable getting these finished.

I’ve actually had this planned for a total reset for a long time. What I’m going to do in the future is probably use this PR as a tracker/workzone, and independently pr each map as I finish them

**Comment by traunts** [comment]
Closing as the repository is archived.

**Pull request closed without merging**
