### PR TITLE
Version number and relative positions

### PR DESCRIPTION
**Pull request by orengg**
* Add version number label.
* Changes that make GUI elements' position to be relative to their appropriate container.

Dependent on [#214 in the source repo](https://github.com/cortex-command-community/Cortex-Command-Community-Project-Source/pull/214)

### CODE REVIEW

**Review by garethyr — APPROVED** [review]
Good stuff.
Did you use the GUI editor tool for this or did you tweak it all manually?

**Comment by orengg** [comment]
I did it manually, though not by eye. I did calculations to have the correct new positions. The collection box sizes are by eye because they don't really matter as long as they're big enough.

**Comment by garethyr** [comment]
Cool, I was curious what option you went with and how much of a pain it was.

**Comment by orengg** [comment]
It was a bit of a pain but I've never used the GUI editor so I can't compare.

**Review by MaximDude — APPROVED** [review]

**Pull request merged**
